- name: Window Management 
  keybinds:
    - name: Toggle Master/Dwindle Layout
      key: Win + Space
    - name: Move Window
      key: Win + Mouse Left Button
    - name: Resize Window
      key: Win + Mouse Right Button
    - name: Kill Active Window
      key: Win + C
    - name: Close Window
      key: Win + Shift + C
    - name: Focusing on Windows
      key: Win + Arrow Keys
    - name: Moving Windows
      key: Shift + Win + Arrow Keys
    - name: Toggle Floating Window
      key: Win + F
    - name: Toggle Pseudo Mode
      key: Win + P
    - name: Toggle Fullscreen Window
      key: Win + Shift + Space
    - name: Toggle Window Swap
      key: Win + S
    - name: Split Window in Ratio
      key: Win + M / Win + Shift + M
    - name: Resize Window
      key: Win + Alt + Arrow Keys
    - name: Moving Windows (Floating Mode)
      key: Win + Ctrl + Arrow Keys

- name: Group Management 
  keybinds:
    - name: Toggle Group
      key: Win + G
    - name: Change Active Group
      key: Alt + Tab

- name: Workspace Management 󱁐
  keybinds:
    - name: Moving to a specific Workspace
      key: Win + 1-10
    - name: Moving Windows to other specific Worskpace
      key: Win + Shift + 1-10
    - name: Moving Windows to other specific Workspace (Silent)
      key: Shift + Alt + 1-10
    - name: Moving to the next Workspace (Mouse)
      key: Win + Mouse Wheel Down / Up
    - name: Moving to the next Worskpace (Keyboard)
      key: Shift + Alt + A / D
    - name: Toggle Float in Selected Workspace
      key: Win + Shift + F
    - name: Toggle Pseudo in Selected Workspace
      key: Win + Shift + P

- name: Apps 󰙵
  keybinds:
    - name: Launch Browser
      key: Alt + F
    - name: Launch Editor / IDE
      key: Win + Backspace / Win + Shift + Backspace
    - name: Launch File Manager
      key: Win +  E
    - name: Launch Terminal
      key: Win + Enter
    - name: Launch Floating Terminal
      key: Shift + Alt + Enter
    - name: Launch FullScreen Terminal
      key: Ctr + Alt + Enter
    - name: Launch Yazi
      key: Alt + Y
    - name: Open Launcher
      key: Win + D / Win

- name: Features 󰒉
  keybinds:
    - name: Random Wallpaper
      key: Shift + Alt + W
    - name: Wallpaper Picker
      key: Win + Shift + W
    - name: Clipboard
      key: Shift + Alt + C
    - name: Notes
      key: Win + N
    - name: Tmux Session
      key: Win + T
    - name: Emoji Picker
      key: Alt + Slash
    - name: Quick Links
      key: Alt + Q
    - name: Quick Edit Hyprland Settings
      key: Alt + E
    - name: Todo List
      key: Shift + Alt + T
    - name: Toggle Blur
      key: Win + Shift + Q
    - name: Switch Keyboard Layout
      key: Alt + F1
    - name: PowerMenu
      key: Win + X
    - name: Recorder
      key: Win + R
    - name: Stop Recorder
      key: Win + Shift + R
    - name: Online Music
      key: Alt + M
    - name: Keybindings Picker
      key: Win + F1
    - name: Toggle Waybar Layout
      key: Alt + W

- name: Online Music Controller 󰽰
  keybinds:
    - name: Stop Track
      key: Alt + S
    - name: Next Track
      key: Alt + N
    - name: Previous Track
      key: Alt + P
    - name: Resume / Pause Track
      key: Alt + R

- name: Screenshots 󰹑
  keybinds:
    - name: Screenshoot Fullscreen
      key: Print
    - name: Screenshoot Selection
      key: Win + Z
    - name: Screenshoot In 5sec
      key: Alt + Print
    - name: Screenshoot In 10sec
      key: Shift + Print

- name: Misc 
  keybinds:
    - name: Toggle Opaque
      key: Win + Shift + O
    - name: Exit Hyprland
      key: Ctrl + Alt + Delete
    - name: Hide bar
      key: Win + H
    - name: Refresh waybar, swaync, rofi
      key: Win + Alt + R
