- name: Keybinds
  keybinds:
    - name: Enter Insert Mode
      key: a
    - name: Open in new tab
      key: t
    - name: Openin new window
      key: O
    - name: Open in Private window
      key: P
    - name: Clone tab in new widnow
      key: W
    - name: Switch to previous tab
      key: H
    - name: Switch to the next tab
      key: L
    - name: Go back in histroy
      key: K
    - name: Go forward in history
      key: J
    - name: Zoom in
      key: Ctrl + +
    - name: Zoom out
      key: Ctrl + -
    - name: Toggle status bar visibility
      key: space + b
    - name: Toggle tab bar visibility
      key: space + B
    - name: Edit cofiguration file
      key: space + c
    - name: Set command in command mode
      key: space + C
    - name: Open devtools
      key: space + d
    - name: Focus on devtools
      key: space + D
    - name: Edit text
      key: space + e
    - name: Edit command in $EDITOR
      key: space + E
    - name: Open multiple links
      key: space + f
    - name: View history
      key: space + h
    - name: Open help page
      key: space + H
   - name: List bookmarks
      key: space + m
   - name: Add bookmarks
      key: space + M
   - name: Clone current tab
      key: space + n
   - name: Open link in new window
      key: space + o
   - name: Open link in private window
      key: space + O
   - name: Pin current tab
      key: space + p
   - name: Move tab to a new position
      key: space + P
   - name: Close current tab
      key: space + q
   - name: Close the browser
      key: space + Q
   - name: Reload configuration file
      key: space + r
   - name: Restart the browser
      key: space + R
   - name: Take a screenshot
      key: space + s
   - name: View page source in editor
      key: space + S
   - name: Open tab switcher
      key: space + t
   - name: Close other tabs
      key: space + T
   - name: Undo last action
      key: space + u
   - name: Open link in mpv
      key: space + v
   - name: Open link in youtube-dl
      key: space + V
   - name: Open tab in another window
      key: space + w
   - name: Take tab from another window
      key: space + W
   - name: Yank link
      key: space + y
   - name: Quit the browser
      key: space + x
   - name: Close other windows
      key: space + X
