# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e5e1e9"

# Title color for boxes
theme[title]="#c6c0ff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c8c3dc"

# Background color of selected item in processes box
theme[selected_bg]="#c6c0ff"

# Foreground color of selected item in processes box
theme[selected_fg]="#2e295f"

# Color of inactive/disabled text
theme[inactive_fg]="#c9c5d0"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ebb8cf"

# Cpu box outline color
theme[cpu_box]="#928f99"

# Memory/disks box outline color
theme[mem_box]="#928f99"

# Net up/down box outline color
theme[net_box]="#928f99"

# Processes box outline color
theme[proc_box]="#928f99"

# Box divider line and small boxes line color
theme[div_line]="#47464f"

# Temperature graph colors
theme[temp_start]="#c8c3dc"
theme[temp_mid]="#c6c0ff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c8c3dc"
theme[cpu_mid]="#c6c0ff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c8c3dc"
theme[free_mid]=""
theme[free_end]="#474459"

# Mem/Disk cached meter
theme[cached_start]="#ebb8cf"
theme[cached_mid]=""
theme[cached_end]="#613b4e"

# Mem/Disk available meter
theme[available_start]="#c6c0ff"
theme[available_mid]=""
theme[available_end]="#454078"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c8c3dc"
theme[download_mid]="#c6c0ff"
theme[download_end]="#ebb8cf"

# Upload graph colors
theme[upload_start]="#c8c3dc"
theme[upload_mid]="#c6c0ff"
theme[upload_end]="#ebb8cf"
