# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#f1dfd9"

# Title color for boxes
theme[title]="#ffb597"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e7beae"

# Background color of selected item in processes box
theme[selected_bg]="#ffb597"

# Foreground color of selected item in processes box
theme[selected_fg]="#552107"

# Color of inactive/disabled text
theme[inactive_fg]="#d8c2ba"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d3c78f"

# Cpu box outline color
theme[cpu_box]="#a08d86"

# Memory/disks box outline color
theme[mem_box]="#a08d86"

# Net up/down box outline color
theme[net_box]="#a08d86"

# Processes box outline color
theme[proc_box]="#a08d86"

# Box divider line and small boxes line color
theme[div_line]="#53433e"

# Temperature graph colors
theme[temp_start]="#e7beae"
theme[temp_mid]="#ffb597"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#e7beae"
theme[cpu_mid]="#ffb597"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#e7beae"
theme[free_mid]=""
theme[free_end]="#5d4034"

# Mem/Disk cached meter
theme[cached_start]="#d3c78f"
theme[cached_mid]=""
theme[cached_end]="#4f471b"

# Mem/Disk available meter
theme[available_start]="#ffb597"
theme[available_mid]=""
theme[available_end]="#71361b"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#e7beae"
theme[download_mid]="#ffb597"
theme[download_end]="#d3c78f"

# Upload graph colors
theme[upload_start]="#e7beae"
theme[upload_mid]="#ffb597"
theme[upload_end]="#d3c78f"
