$modus = /home/sankalp/.config/Modus
exec-once = cd $modus && uwsm app -- uv run main.py
exec = pgrep -x "hypridle" > /dev/null || uwsm app -- hypridle
exec-once = uwsm app -- awww-daemon
exec-once =  wl-paste --type text --watch cliphist store
exec-once =  wl-paste --type image --watch cliphist store


$fabricSend = uwsm app -- fabric-cli exec modus
# Reload Modus
bind = ALT SHIFT, R, exec, killall modus; cd $modus  && uwsm app -- uv run main.py

# App Launcher
bind = SUPER, D, exec, $fabricSend "launcher.toggle()"

# Emoji Selector
bind = SUPER, E, exec, $fabricSend "launcher.toggle('em')"

# CLipboard
bind = SUPER, V, exec, $fabricSend "launcher.toggle('clip')"

# wallpaper
bind = SUPER, W, exec, $fabricSend "launcher.toggle('wall')"

# Powermenu
bind = SUPER, X, exec, $fabricSend "launcher.toggle('pm')"

# ScreenCapture
bind = SUPER, Z, exec, $fabricSend "launcher.toggle('sc')"

# Otp
bind = SUPER, O, exec, $fabricSend "launcher.toggle('otp')"

# Password Manager
bind = SUPER SHIFT, P, exec, $fabricSend "launcher.toggle('pass')"

# Bookmark manager
# bind = SUPER, K, exec, $fabricSend "launcher.toggle('bm')"

# Screenshot region
bind = SUPER, S, exec, $fabricSend "launcher.toggle('sc region', external=True)"

# Random Wallpaper
bind = ALT SHIFT, W, exec, $fabricSend "launcher.toggle('wr', external=True)"

# Google Search
bind = SUPER, G, exec, $fabricSend "launcher.toggle('gg')"

# Window Switcher
bind = ALT, W, exec, $fabricSend "launcher.toggle('win')"

# Tmux
bind = SUPER, T, exec, $fabricSend "launcher.toggle('tmux')"

# KB_Layout Switcher
bind = ALT, SPACE, exec, $fabricSend "switch_keyboard_layout()"

source = /home/sankalp/.config/Modus/config/hypr/colors.conf

layerrule = match:namespace fabric, no_anim on

general {
    col.active_border = rgb($primary)
    col.inactive_border = rgb($surface)
    gaps_in = 2
    gaps_out = 4
    border_size = 2
    layout = scrolling
}

cursor {
  no_warps=true
}

decoration {
    blur {
        enabled = yes
        size = 5
        passes = 3
        new_optimizations = yes
        contrast = 1
        brightness = 1
    }
    rounding = 14
    shadow {
      enabled = true
      range = 10
      render_power = 2
      color = rgba(0, 0, 0, 0.25)
    }
}

animations {
    enabled = yes
    bezier = myBezier, 0.4, 0.0, 0.2, 1.0
    animation = windows, 1, 2.5, myBezier, popin 80%
    animation = border, 1, 2.5, myBezier
    animation = fade, 1, 2.5, myBezier
    animation = workspaces, 1, 2.5, myBezier, slidefade 20%
}
