DEFAULT = {
    "debug": {"enabled": False},
    "wallpaper_dir": {"path": "~/Pictures/Wallpapers/"},
    "corners": {"enabled": True},
    "keyboard_layout": {"layouts": ["us"]},
    "panel": {
        "enabled": True,
        "position": "top",
        "autohide": True,
        "systray": {"enabled": True, "hide_items": []},
        "network": {"enabled": True},
        "bluetooth": {"enabled": True},
        "workspace": {"enabled": True, "hide_special_ws": True},
        "datetime": {"enabled": True, "12hrs": True},
        "taskbar": {
            "enabled": True,
            "hide_empty": True,
            "hide_special": True,
            "icon_size": 20,
            "group_apps": False,
        },
        "battery": {
            "enabled": True,
            "label": True,
            "hide_on_full": True,
            "icon_size": 28,
        },
    },
    "osd": {
        "enabled": True,
        "position": "bottom",
        "audio": True,
        "brightness": True,
        "capslock": True,
        "kb_layout": True,
        "network": True,
        "microphone": True,
        "battery": True,
        "cooldown_ms": 200,
    },
    "notifications": {
        "enabled": True,
        "timeout": "10s",
        "image_size": 64,
        "width": 360,
        "buttons_per_row": 3,
        "corner_size": 16,
        "revealer_duration": 400,
    },
    "desktop_widget": {
        "enabled": True,
        "time_format": "12 hrs",
        "date_format": "%A. %d %B",
        "anchor": "top",
        "margin": "220px 0px 0px 0px",
    },
}
