[pyprland]
plugins = ["scratchpads", "expose", "magnify"]

[scratchpads.terminal]
command = "kitty --class scratchpad-large"
excludes = ["yazi", "btop"]
lazy = true

[scratchpads.yazi]
command = "kitty --class scratchpad-large yazi"
lazy = true

[scratchpads.nvim]
command = "kitty --class scratchpad-large nvim"
lazy = true

[scratchpads.btop]
command = "kitty --class scratchpad-large btop"
lazy = true

[scratchpads.cava]
command = "kitty --class scratchpad-mini cava"
lazy = true

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "40% 50%"
