[pyprland]
plugins = ["scratchpads", "expose", "magnify"]

[scratchpads.terminal]
command = "kitty --class scratchpad-large"
excludes = ["yazi", "btop"]
lazy = true

[scratchpads.yazi]
command = "kitty --class scratchpad-large yazi"
lazy = true

[scratchpads.gpt]
command = "kitty --class scratchpad-large tgpt -m"
lazy = true

[scratchpads.btop]
command = "kitty --class scratchpad-large btop"
lazy = true

[scratchpads.cava]
command = "kitty --class scratchpad-mini cava"
lazy = true

[scratchpads.bluetooth]
command = "blueman-manager"
animation = "fromRight"
unfocus = "hide"
margin = 20
lazy = true

