classic: false
ignore-globs:
  - .git
  - .gitignore
  - .config/KADOKAWA
  - .config/Kid3
  - .config/lsd
  - .config/lite-xl/plugins
  - .config/lite-xl/widget
  - .config/lite-xl/ws
  - .config/nvim/LICENSE
  - .config/nvim/screenshots
  - .config/nvim/plugins
  - .config/mimeapps.list
  - .gnupg
  - .icons/default
  - .local/share/applications
  - .local/share/lite-xl
  - .local/share/fish
  - .mongodb
  - .mycli-history
  - .myclirc
  - .ovsx_vsce
  - .gitconfig
  - .git-credentials
  - .vsce
  - .xsessionrc
  - .zsh_history
  - .python_history
  - .psql_history
  - .python_history
  - .nvidia-settings-rc
  - .ssh
  - .oh-my-zsh
  - python
  - Templates
