# User Settings
# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables

dwindle {
  pseudotile = yes
  preserve_split = yes
  smart_resizing = true
  use_active_for_splits = true
  smart_split = false
  default_split_ratio = 1.0
  split_bias = 0
  precise_mouse_move = false
  special_scale_factor = 0.8
}

master {
  new_status = slave
  new_on_top =  false
  new_on_active = none
  orientation = left
  mfact = 0.55
  slave_count_for_center_master = 2
	center_master_fallback        = left
	smart_resizing                = true
	drop_at_cursor                = true
	always_keep_position          = false
}

scrolling {
    column_width = 0.50
    fullscreen_on_one_column = true
    direction = right
    follow_focus = true
}

monocle {
}

input {
  kb_layout = us,np
  kb_variant =
  kb_model =
  # kb_options = grp:alt_space_toggle
  kb_rules =
  repeat_rate = 50
  repeat_delay = 300
  numlock_by_default = true
  left_handed = 0
  follow_mouse = 1
  float_switch_override_focus = 0

  touchpad {
  disable_while_typing = 1
  natural_scroll = 0
  clickfinger_behavior = 0
  middle_button_emulation = 1
  tap-to-click = 1
  drag_lock = 0
 }
}


gesture {
    gesture = 3, horizontal, workspace,
    # gesture = 3, down, close,
    gesture = 3, up, dispatcher, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 1.5}')"
    gesture = 3, down, dispatcher, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 1.5}')"
    gesture = 4, down, float
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vfr = 1
  vrr = 2
  mouse_move_enables_dpms = true
  enable_swallow = false
  focus_on_activate = false
  swallow_regex = (foot|kitty|alacritty|Alacritty)
  middle_click_paste = false
}

binds {
  workspace_back_and_forth=1
  allow_workspace_cycles=1
  pass_mouse_when_bound=0
}

xwayland {
    enabled = true
    force_zero_scaling = true
}

cursor {
    sync_gsettings_theme = true
    no_hardware_cursors = false
    enable_hyprcursor = true
    warp_on_change_workspace = true
    no_warps = true
    min_refresh_rate = 24
}

ecosystem{
        no_update_news = true
        no_donation_nag = true
    }


