# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds

# SUPER KEY
$mainMod = SUPER

$terminal = kitty
$filemanager = thunar
$telegram = materialgram
$browser = zen-browser

# Testing
bind = Alt, f12,                exec, notify-send 'Test notification' "Here's a really long message to test truncation and wrapping\nYou can middle click or flick this notification to dismiss it!" -a 'terminal' -A "Test1=I got it!" -A "Test2=Another action"
bind = Alt, Equal,              exec, notify-send 'hmm' ${SLURP_ARGS}

$axMessage = notify-send "Axenide" "FIRE IN THE HOLE‼️🗣️🔥🕳️" -i "/home/sankalp/.config/Ax-Shell/assets/ax.png" -A "🗣️" -A "🔥" -A "🕳️" -a "Source Code"

bind = SUPER ALT, N, exec, $axMessage # Message
# Applications
bind = ALT SHIFT,Return,    exec, $terminal --title float_kitty --single-instance
bind = $mainMod, Return,        exec,$terminal
# bind = ALT SHIFT,Return,        exec, [float] uwsm app -- $terminal -1
bind = ALT, E,                  exec, uwsm app -- $filemanager
bind = $mainMod, B,             exec, uwsm app -- $browser
bind = ALT, T,                  exec, uwsm app -- $telegram

bind = $mainMod SHIFT, y,       exec, grimblast save active ~/Pictures/Screenshots/

# Actions
bind = $mainMod CTRL, L,        exec, pidof hyprlock || hyprlock -q
bind = $mainMod CTRL, P,        exec, systemctl poweroff
bind = $mainMod CTRL, R,        exec, systemctl reboot

# Send window to special workspace
bind = ALT, Q, movetoworkspacesilent, special
# Show special workspace + enter control mode
bind = SHIFT ALT, Q, exec, hyprctl dispatch togglespecialworkspace
bind = SHIFT ALT, Q, submap, special

submap = special
bind = , ESCAPE, exec, hyprctl dispatch togglespecialworkspace
bind = , ESCAPE, submap, reset
bind = , RETURN, movetoworkspacesilent, e+0
bind = , RETURN, submap, reset
submap = reset


# scrolling
bind = ALT, D, layoutmsg, move +col
bind = ALT, A, layoutmsg, move -col
bind = $mainMod SHIFT, period, layoutmsg, movewindowto r
bind = $mainMod SHIFT, comma, layoutmsg, movewindowto l
bind = $mainMod SHIFT, up, layoutmsg, movewindowto u
bind = $mainMod SHIFT, down, layoutmsg, movewindowto d
bindd = $mainMod SHIFT, comma, swap columns, layoutmsg, swapcol l

