# Core Colors
background            #0f1511
foreground            #dee4de
selection_foreground  #8ed5b0
selection_background  #003824
cursor                #8ed5b0
cursor_text_color     #0f1511

# Regular Colors
color0  #0f1511
color1  #ffb4ab
color2  #8ed5b0
color3  #a5cdde
color4  #aaf2cb
color5  #d0e8d8
color6  #b4ccbd
color7  #dee4de

# Bright Colors
color8  #353b36
color9  #ffb4ab
color10 #8ed5b0
color11 #a5cdde
color12 #aaf2cb
color13 #d0e8d8
color14 #b4ccbd
color15 #dee4de
