# Core Colors
background            #1a120e
foreground            #f0dfd8
selection_foreground  #ffb693
selection_background  #542104
cursor                #ffb693
cursor_text_color     #1a120e

# Regular Colors
color0  #1a120e
color1  #ffb4ab
color2  #ffb693
color3  #d0c890
color4  #ffdbcc
color5  #ffdbcc
color6  #e6beac
color7  #f0dfd8

# Bright Colors
color8  #423732
color9  #ffb4ab
color10 #ffb693
color11 #d0c890
color12 #ffdbcc
color13 #ffdbcc
color14 #e6beac
color15 #f0dfd8
