[config]
reload_apps = true

[config.reload_apps_list]
kitty = true
gtk_theme = true

[config.wallpaper]
command = "swww"
arguments = [ "img", "-t", "fade", "--transition-duration", "0.5", "--transition-step", "255", "--transition-fps", "60", "-f", "Nearest",]
set = true

[templates.pywal]
input_path = "~/.config/matugen/templates/pywal-colors"
output_path = "~/.cache/wal/colors"

[templates.nvim]
input_path = "~/.config/nvim/pywal/matugen.lua"
output_path = "~/.cache/wal/base46-dark.lua"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.qt5ct]
input_path = "~/.config/matugen/templates/qtct-colors.conf"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[templates.qt6ct]
input_path = "~/.config/matugen/templates/qtct-colors.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"

[templates.hyprland]
input_path = "~/.config/Modus/config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/Modus/config/hypr/colors.conf"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "killall -SIGUSR1 kitty &"

# [templates.starship]
# input_path = "~/.config/matugen/templates/starship-colors.toml"
# output_path = "~/.config/starship.toml"
# post_hook = "starship init zsh > ~/.zshrc"

[templates.Telegram]
input_path = "~/.config/matugen/templates/telegram-colors.tdesktop-theme"
output_path = "~/.config/telegram-desktop/themes/material-you.tdesktop-theme"

[templates.discord]
input_path = "~/.config/matugen/templates/discord.css"
output_path = "~/.config/vesktop/themes/quickCss.css"

[templates.cava]
input_path = "~/.config/matugen/templates/cava"
output_path = "~/.config/cava/config"

[templates.yazi]
input_path = "~/.config/matugen/templates/colors-yazi.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.zathura]
input_path = "~/.config/matugen/templates/zathurarc"
output_path = "~/.config/zathura/colors"

[templates.modus]
input_path = "~/.config/Modus/config/matugen/templates/modus.css"
output_path = "~/.config/Modus/styles/colors.css"
post_hook = "fabric-cli exec modus 'app.set_css()' &"

[templates.ax-shell]
input_path = "~/.config/Ax-Shell/config/matugen/templates/ax-shell.css"
output_path = "~/.config/Ax-Shell/styles/colors.css"
post_hook = "fabric-cli exec ax-shell 'app.set_css()' &"

[templates.modusv1]
input_path = "~/Modus/config/matugen/templates/modusv1.css"
output_path = "~/Modus/styles/colors.css"
post_hook = "fabric-cli exec modusv1 'app.set_css()' &"

[templates.hyprfabricated]
input_path = "~/.config/hyprfabricated/config/matugen/templates/hyprfabricated.css"
output_path = "~/.config/hyprfabricated/styles/colors.css"
post_hook = "fabric-cli exec hyprfabricated 'app.set_css()' &"

[templates.yz-shell]
input_path = "~/.config/YZ-Shell/config/matugen/templates/yz-shell.css"
output_path = "~/.config/YZ-Shell/styles/colors.css"
post_hook = "fabric-cli exec yz-shell 'app.set_css()' &"

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
