"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
  { on = [
    "<C-s>",
  ], run = '''shell "$SHELL" --block --confirm''', desc = "Open shell here" },
]

append_keymap = [
  { on = [
    "e",
  ], run = "open", desc = "Open the selected files" },
  { on = [
    "E",
  ], run = "open --interactive", desc = "Open the selected files interactively" },
  { on = [
    "g",
    "n",
  ], run = "cd ~/.config/nvim", desc = "Go to the nvim directory" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/Videos", desc = "Go to the videos directory" },
  { on = [
    "g",
    "i",
  ], run = "cd ~/Imagenes", desc = "Go to the images directory" },
  { on = [
    "g",
    "D",
  ], run = "cd ~/Documentos", desc = "Go to the docs directory" },
  { on = [
    "g",
    "o",
  ], run = "cd ~/Documentos/Obsidian/obsidianVault/", desc = "Go to the obsidian directory" },
  { on = [
    "g",
    "r",
  ], run = "cd ~/Repos", desc = "Go to the repos directory" },
]

[input]

prepend_keymap = [{ on = ["<Esc>"], run = "close", desc = "Cancel input" }]
