[manager]
cwd = { fg = "#b4ccbd", bold=true}

hovered         = { fg = "#aaf2cb", bg = "#005236" }
preview_hovered = { underline = true, bold=true }


[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#aaf2cb", bg = "#005236" }

# Mode
mode_normal = { fg = "#003824",   bg = "#8ed5b0", bold = true }
mode_select = { fg = "#20352a", bg = "#b4ccbd", bold = true }
mode_unset  = { fg = "#063543",  bg = "#a5cdde", bold = true }

[which]
mask            = { bg = "#1b211d" }
cand            = { fg = "#8ed5b0" }
desc            = { fg = "#b4ccbd" }
separator       = "  "
separator_style = { fg = "#a5cdde" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#b4ccbd" },

	# Videos
	{ mime = "video/*", fg = "#a5cdde" },
	{ mime = "audio/*", fg = "#a5cdde" },

	# Archives
	{ mime = "application/zip",             fg = "#ffb4ab" },
	{ mime = "application/gzip",            fg = "#ffb4ab" },
	{ mime = "application/x-tar",           fg = "#ffb4ab" },
	{ mime = "application/x-bzip",          fg = "#ffb4ab" },
	{ mime = "application/x-bzip2",         fg = "#ffb4ab" },
	{ mime = "application/x-7z-compressed", fg = "#ffb4ab" },
	{ mime = "application/x-rar",           fg = "#ffb4ab" },

	# Fallback
	{ name = "*", fg = "#8ed5b0", bold=true },
	{ name = "*/", fg = "#b4ccbd", bold=true }
]
