"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_dir_first = true

[opener]
folder = [
  { run = 'hyprctl dispatch run "[float; size 60% 60%; center 1] xdg-open" "$@"', desc = "Open in GUI File Manager" },
  { run = '$EDITOR "$@"' },
]
archive = [{ run = 'xdg-open "$1"', desc = "Extract here" }]
pdf = [{ run = 'xdg-open "$1"', desc = "Open" }]
docx = [{ run = 'xdg-open "$1"', desc = "Open" }]
text = [
  { run = 'pypr hide yazi & kitty --detach $EDITOR "$@"', block = true, desc = "Open" },
]
image = [
  { run = 'xdg-open "$@"', desc = "Open" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF" },
]
video = [
  { run = 'xdg-open "$@"' },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
audio = [
  { run = 'xdg-open "$@"' },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
fallback = [
  { run = 'open "$@"', desc = "Open" },
  { run = 'open -R "$@"', desc = "Reveal in Finder" },
]

[open]
rules = [
  { name = "*/", use = "folder" },

  { mime = "text/*", use = "text" },
  { mime = "text/docx", use = "docx" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "video" },
  { mime = "audio/*", use = "audio" },
  { mime = "inode/x-empty", use = "text" },

  { mime = "application/json", use = "text" },
  { mime = "*/javascript", use = "text" },

  { mime = "application/pdf", use = "pdf" },
  { mime = "application/zip", use = "archive" },
  { mime = "application/gzip", use = "archive" },
  { mime = "application/x-bzip", use = "archive" },
  { mime = "application/x-bzip2", use = "archive" },
  { mime = "application/x-tar", use = "archive" },
  { mime = "application/x-7z-compressed", use = "archive" },
  { mime = "application/x-rar", use = "archive" },

  { mime = "*", use = "fallback" },
]
