#!/usr/bin/env bash

rofi_command="rofi -markup -markup-rows -theme $HOME/.config/rofi/config/recorder/screenshot.rasi -steal-focus "

datetime=$(date +"%Y-%m-%d %I-%M-%S")
dir="/home/$USER/Pictures/Screenshots"
#file="Screenshot from ${date} ${time}.png"

# Icons
icon1="/home/$USER/.config/rofi/recorder/camera-viewfinder.svg"
icon2="/home/$USER/.config/rofi/recorder/timer.svg"


# Buttons
layout=`cat ~/.config/rofi/config/recorder/screenshot.rasi | grep BUTTON | cut -d'=' -f2 | tr -d '[:blank:],*/'`
if [[ $layout == "TRUE" ]]; then
	screen=" <span font='Font Awesome 6 Pro Bold 16' rise='-3pt'> </span>	Capture Desktop"
	area=" <span font='Font Awesome 6 Pro Bold 16' rise='-3pt'> </span>	Capture Area"
	window=" <span font='Font Awesome 6 Pro Bold 16' rise='-3pt'> </span>	Capture Window"
	infivearea=" <span font='Font Awesome 6 Pro Bold 16' rise='-3pt'> </span>	Capture Area in 5s"
	infive=" <span font='Font Awesome 6 Pro Bold 16' rise='-3pt'></span>		Capture in 5s"

else
	screen="  Capture Desktop"
	area="  Capture Area"
	window="  Capture Window"
	infivearea="  Capture Area in 5s"
	infive="  Capture in 5s"
fi

# Notify and view screenshot
notify_view () {
	dunstify -u low --replace=699 -i $icon1 "Copied to clipboard."
	if [[ -e "$dir/Screenshot from ${datetime}.png" ]]; then
		dunstify -u low --replace=699 -i $icon1 "Screenshot Saved."
	else
		dunstify -u low --replace=699 -i $icon1 "Screenshot Deleted."
	fi
}

# countdown
countdown () {
	for sec in `seq $1 -1 1`; do
		dunstify -t 1000 --replace=699 -i $icon2 "Taking shot in : $sec"
		sleep 1
	done
}

# take shots
shotnow () {
	#sleep 0.5 && hyprpicker -r -z -n &
	sleep 0.5 && $HOME/.local/bin/grimblast --freeze copysave screen $dir/"Screenshot from ${datetime}".png
	#wl-copy < $dir/"Screenshot from ${datetime}".png
	#killall hyprpicker
	notify_view
}

shot5 () {
	countdown '5'
	#sleep 1 && hyprpicker -r -z -n &
	sleep 1 && $HOME/.local/bin/grimblast --freeze copysave screen $dir/"Screenshot from ${datetime}".png
	#wl-copy < $dir/"Screenshot from ${datetime}".png
	#killall hyprpicker
	notify_view
}

shot5area () {
	#geometry=$(slurp -b#1e1e1e55 -c#b4befe -w4)
	countdown '5'
	#sleep 1 && hyprpicker -r -z -n &
	sleep 1 && $HOME/.local/bin/grimblast --freeze copysave area $dir/"Screenshot from ${datetime}".png
	#wl-copy < $dir/"Screenshot from ${datetime}".png
	#killall hyprpicker
	notify_view
}

shotwin () {
	#sleep 1 && hyprpicker -r -z -n &
	#grim -g "$(hyprctl activewindow -j | jq -r ".at,.size" | jq -s "add" | jq '_nwise(4)' | jq -r '"\(.[0]),\(.[1]) \(.[2])x\(.[3])"')" $dir/"Screenshot from ${datetime}".png
	$HOME/.local/bin/grimblast --freeze copysave active  $dir/"Screenshot from ${datetime}".png
	#wl-copy < $dir/"Screenshot from ${datetime}".png
	#killall hyprpicker
	notify_view
}

shotarea () {
	#sleep 0.8 && hyprpicker -r -z -n &
	sleep 1 && $HOME/.local/bin/grimblast --freeze copysave area $dir/"Screenshot from ${datetime}".png 
	#wl-copy < $dir/"Screenshot from ${datetime}".png
	#killall hyprpicker
	notify_view
}

if [[ $1 == "copy" ]]; then
	shotarea
	exit 0
else 
	:
fi
	

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

# Variable passed to rofi
options="$screen\n$area\n$window\n$infivearea\n$infive"

chosen="$(echo -e "$options"| $rofi_command -p 'Take A Shot' -dmenu -selected-row 0)" 
case $chosen in
    $screen)
		shotnow
        ;;
    $area)
		shotarea
        ;;
    $window)
		shotwin
		;;
    $infive)
		shot5
		;;
    $infivearea)
		shot5area
        ;;
esac

